name: Build and deploy Node.js app to Azure Web App - OrganizZen
on:
  push:
    branches:
      - manvsatish-organizzen
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Replace ‘20.x’ with '20'
      - name: npm install, build, and test
        run: |
          npm install --workspaces=fale
          npm run -w organizzen-express build --if-present
      working-directory: packages/organizzen-express
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      working-directory: packages/organizzen-express
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OrganizZen'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7BEEBD562073488A8676ED498E98ECEC }}
          package: .
